# Etapa 1: build
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod download
RUN go build -o server . 

# Etapa 2: runtime
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/server .
COPY .env /app/.env 

EXPOSE 8080
CMD ["./server", "--port=8080"]
