server:
  interface: "0.0.0.0"
  port: 8080
  host: "localhost"

redis:
  interface: "tcp"
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
